//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Truking.CRM.WinSrv.cn.truking.sappodev.selectsorder {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_SEL_SORDER_OUTBinding", Namespace="urn:erp:select_sorder")]
    public partial class SI_SEL_SORDER_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_SEL_SORDER_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_SEL_SORDER_OUTService() {
            this.Url = global::Truking.CRM.WinSrv.Properties.Settings.Default.Truking_CRM_WinSrv_cn_truking_sappodev_selectsorder_SI_SEL_SORDER_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_SEL_SORDER_OUTCompletedEventHandler SI_SEL_SORDER_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_SEL_SORDER_RSP", Namespace="urn:erp:select_sorder")]
        public DT_SEL_SORDER_RSP SI_SEL_SORDER_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:erp:select_sorder")] DT_SEL_SORDER_REQ MT_SEL_SORDER_REQ) {
            object[] results = this.Invoke("SI_SEL_SORDER_OUT", new object[] {
                        MT_SEL_SORDER_REQ});
            return ((DT_SEL_SORDER_RSP)(results[0]));
        }
        
        /// <remarks/>
        public void SI_SEL_SORDER_OUTAsync(DT_SEL_SORDER_REQ MT_SEL_SORDER_REQ) {
            this.SI_SEL_SORDER_OUTAsync(MT_SEL_SORDER_REQ, null);
        }
        
        /// <remarks/>
        public void SI_SEL_SORDER_OUTAsync(DT_SEL_SORDER_REQ MT_SEL_SORDER_REQ, object userState) {
            if ((this.SI_SEL_SORDER_OUTOperationCompleted == null)) {
                this.SI_SEL_SORDER_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_SEL_SORDER_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_SEL_SORDER_OUT", new object[] {
                        MT_SEL_SORDER_REQ}, this.SI_SEL_SORDER_OUTOperationCompleted, userState);
        }
        
        private void OnSI_SEL_SORDER_OUTOperationCompleted(object arg) {
            if ((this.SI_SEL_SORDER_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_SEL_SORDER_OUTCompleted(this, new SI_SEL_SORDER_OUTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:erp:select_sorder")]
    public partial class DT_SEL_SORDER_REQ {
        
        private string iT_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IT_DATA {
            get {
                return this.iT_DATAField;
            }
            set {
                this.iT_DATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:erp:select_sorder")]
    public partial class DT_SEL_SORDER_RSP {
        
        private string eT_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ET_RETURN {
            get {
                return this.eT_RETURNField;
            }
            set {
                this.eT_RETURNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SI_SEL_SORDER_OUTCompletedEventHandler(object sender, SI_SEL_SORDER_OUTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_SEL_SORDER_OUTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_SEL_SORDER_OUTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_SEL_SORDER_RSP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_SEL_SORDER_RSP)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591