//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Truking.CRM.WinSrv.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sappodev.truking.cn:50000/XISOAPAdapter/MessageServlet?senderParty=&sender" +
            "Service=BS_ERP_S4&receiverParty=&receiverService=&interface=SI_SEL_SORDER_OUT&in" +
            "terfaceNamespace=urn%3Aerp%3Aselect_sorder")]
        public string Truking_CRM_WinSrv_cn_truking_sappodev_selectsorder_SI_SEL_SORDER_OUTService {
            get {
                return ((string)(this["Truking_CRM_WinSrv_cn_truking_sappodev_selectsorder_SI_SEL_SORDER_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sappodev.truking.cn:50000/XISOAPAdapter/MessageServlet?senderParty=&sender" +
            "Service=BS_ERP_S4&receiverParty=&receiverService=&interface=SI_CUSTOMERRECOGNITI" +
            "ON_OUT&interfaceNamespace=urn%3Aerp%3Aselect_customerrecognition")]
        public string Truking_CRM_WinSrv_cn_truking_sappodev_recognition_SI_CUSTOMERRECOGNITION_OUTService {
            get {
                return ((string)(this["Truking_CRM_WinSrv_cn_truking_sappodev_recognition_SI_CUSTOMERRECOGNITION_OUTServ" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sappodev.truking.cn:50000/XISOAPAdapter/MessageServlet?senderParty=&sender" +
            "Service=BS_CRM&receiverParty=&receiverService=&interface=SI_EXCHANGE_RATE_OUT&in" +
            "terfaceNamespace=urn%3Acrm%3Aexchange_rate")]
        public string Truking_CRM_WinSrv_cn_truking_sappodev_rate_SI_EXCHANGE_RATE_OUTService {
            get {
                return ((string)(this["Truking_CRM_WinSrv_cn_truking_sappodev_rate_SI_EXCHANGE_RATE_OUTService"]));
            }
        }
    }
}
